import type { NextPage } from 'next';
import Head from 'next/head';
import Image from 'next/image';
import styles from '../styles/Home.module.css';
import Input from '../components/elements/Input';

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>M&Z Electrical Service</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <Input
          htmlFor="test"
          labelText="Test"
          type="text"
          placeholder="Test"
          value="Test"
          onChange={(e) => {
            console.log(e.target.value);
          }}
        />
      </main>

      <footer className={styles.footer}></footer>
    </div>
  );
};

export default Home;
