import type { NextPage } from 'next';
import Head from 'next/head';
import Image from 'next/image';

import Layout from '../components/elements/Layout';
import FrontPage from '../components/FrontPage/FrontPage';
import Services from '../components/Services/Services';
import Sample2 from '../components/Sample2';
import About from '../components/About/About';
import Shape2 from '../components/elements/Shape2';

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>M&Z Electrical Service</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout>
        <FrontPage />
        <Services />
        <About />
        <Shape2 />
      </Layout>
    </div>
  );
};

export default Home;
